///*****************************************
//  Copyright (C) 2009-2025
//  ITE Tech. Inc. All Rights Reserved
//  Proprietary and Confidential
///*****************************************
//   @file   <515XRAM.H>
//   @author ITE
//   @date   2025/02/11
//   @fileversion: ITE_HDMIRX_SAMPLE_V2.13
//******************************************/

#ifndef _515xram_
#define _515xram_
/*
#define MySon
#ifdef MySon
extern // xdata  PADMOD0        _at_  0x0f50;

extern // xdata  PORT4OE        _at_  0x0f57;
#else

#endif
*/
#endif
